import { prisma } from "./../prisma";

async function addClients(data, { user }) {
  const {
    firstName,
    lastName,
    companyName,
    email,
    clientType,
    address1,
    zipCode,
    city,
    state,
  } = data;

  const client = await prisma.client.create({
    data: {
      firstName,
      lastName,
      fullName: `${firstName} ${lastName}`,
      email,
      clientType,
      userId: user.id,
      address: { create: { address1, zipCode, city, state } },
      companyName,
    },
  });

  return client;
}

const clients = [
  {
    id: 1,
    firstName: "Lammond",
    lastName: "Sweetnam",
    email: "lsweetnam0@bigcartel.com",
    clientType: "COMPANY",
    companyName: "Johns, Stiedemann and Willms",
    dateCreated: "7/20/2021",
    address1: "9 Superior Court",
    zipCode: "56372",
    city: "Saint Cloud",
    state: "MN",
    fullName: "Lammond Sweetnam",
  },
  {
    id: 2,
    firstName: "Danit",
    lastName: "Rowberry",
    email: "drowberry1@icq.com",
    clientType: "COMPANY",
    companyName: "Gleichner-Kerluke",
    dateCreated: "8/14/2021",
    address1: "30 Redwing Circle",
    zipCode: "91913",
    city: "Chula Vista",
    state: "CA",
    fullName: "Danit Rowberry",
  },
  {
    id: 3,
    firstName: "Bord",
    lastName: "Wines",
    email: "bwines2@list-manage.com",
    clientType: "COMPANY",
    companyName: "Bogan, Hermann and Howell",
    dateCreated: "1/26/2021",
    address1: "18 Veith Point",
    zipCode: "90015",
    city: "Los Angeles",
    state: "CA",
    fullName: "Bord Wines",
  },
  {
    id: 4,
    firstName: "Yance",
    lastName: "Dell Casa",
    email: "ydellcasa3@apache.org",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "8/31/2021",
    address1: "129 East Parkway",
    zipCode: "10606",
    city: "White Plains",
    state: "NY",
    fullName: "Yance Dell Casa",
  },
  {
    id: 5,
    firstName: "Morse",
    lastName: "Cleminson",
    email: "mcleminson4@cyberchimps.com",
    clientType: "COMPANY",
    companyName: "Yost LLC",
    dateCreated: "7/2/2021",
    address1: "0182 Village Alley",
    zipCode: "67205",
    city: "Wichita",
    state: "KS",
    fullName: "Morse Cleminson",
  },
  {
    id: 6,
    firstName: "Georges",
    lastName: "Ennever",
    email: "gennever5@hostgator.com",
    clientType: "COMPANY",
    companyName: "Huel Inc",
    dateCreated: "10/4/2020",
    address1: "54 Delaware Way",
    zipCode: "33069",
    city: "Pompano Beach",
    state: "FL",
    fullName: "Georges Ennever",
  },
  {
    id: 7,
    firstName: "Janifer",
    lastName: "Boother",
    email: "jboother6@google.ru",
    clientType: "COMPANY",
    companyName: "Barrows, Bogan and Reynolds",
    dateCreated: "11/17/2020",
    address1: "1540 Mayer Avenue",
    zipCode: "20029",
    city: "Washington",
    state: "DC",
    fullName: "Janifer Boother",
  },
  {
    id: 8,
    firstName: "Ruthi",
    lastName: "Makin",
    email: "rmakin7@paypal.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "9/6/2021",
    address1: "3 Blue Bill Park Hill",
    zipCode: "31416",
    city: "Savannah",
    state: "GA",
    fullName: "Ruthi Makin",
  },
  {
    id: 9,
    firstName: "Eadith",
    lastName: "Cristofari",
    email: "ecristofari8@sphinn.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "2/7/2021",
    address1: "116 Sloan Crossing",
    zipCode: "23514",
    city: "Norfolk",
    state: "VA",
    fullName: "Eadith Cristofari",
  },
  {
    id: 10,
    firstName: "Ruby",
    lastName: "Plaide",
    email: "rplaide9@skyrock.com",
    clientType: "COMPANY",
    companyName: "Kemmer-Nicolas",
    dateCreated: "12/29/2020",
    address1: "366 Bonner Center",
    zipCode: "28242",
    city: "Charlotte",
    state: "NC",
    fullName: "Ruby Plaide",
  },
  {
    id: 11,
    firstName: "Muffin",
    lastName: "Hallex",
    email: "mhallexa@ehow.com",
    clientType: "COMPANY",
    companyName: "Runolfsson, Feeney and Pacocha",
    dateCreated: "6/2/2021",
    address1: "94731 Hudson Drive",
    zipCode: "30045",
    city: "Lawrenceville",
    state: "GA",
    fullName: "Muffin Hallex",
  },
  {
    id: 12,
    firstName: "Briggs",
    lastName: "Doldon",
    email: "bdoldonb@sun.com",
    clientType: "COMPANY",
    companyName: "Harvey Inc",
    dateCreated: "1/26/2021",
    address1: "292 Nova Crossing",
    zipCode: "98411",
    city: "Tacoma",
    state: "WA",
    fullName: "Briggs Doldon",
  },
  {
    id: 13,
    firstName: "Aleece",
    lastName: "Gettings",
    email: "agettingsc@psu.edu",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "3/9/2021",
    address1: "26 Stuart Terrace",
    zipCode: "87195",
    city: "Albuquerque",
    state: "NM",
    fullName: "Aleece Gettings",
  },
  {
    id: 14,
    firstName: "Sherwynd",
    lastName: "Pouton",
    email: "spoutond@quantcast.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "4/17/2021",
    address1: "6 Banding Parkway",
    zipCode: "11024",
    city: "Great Neck",
    state: "NY",
    fullName: "Sherwynd Pouton",
  },
  {
    id: 15,
    firstName: "Elizabeth",
    lastName: "Paulucci",
    email: "epauluccie@stumbleupon.com",
    clientType: "COMPANY",
    companyName: "Morar-Sanford",
    dateCreated: "9/9/2020",
    address1: "652 Algoma Place",
    zipCode: "11044",
    city: "New Hyde Park",
    state: "NY",
    fullName: "Elizabeth Paulucci",
  },
  {
    id: 16,
    firstName: "Zenia",
    lastName: "D'Onise",
    email: "zdonisef@infoseek.co.jp",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "8/16/2021",
    address1: "7228 Novick Way",
    zipCode: "97216",
    city: "Portland",
    state: "OR",
    fullName: "Zenia D'Onise",
  },
  {
    id: 17,
    firstName: "Dieter",
    lastName: "McKinney",
    email: "dmckinneyg@senate.gov",
    clientType: "COMPANY",
    companyName: "Lebsack-Pfeffer",
    dateCreated: "3/24/2021",
    address1: "3 Clemons Court",
    zipCode: "85005",
    city: "Phoenix",
    state: "AZ",
    fullName: "Dieter McKinney",
  },
  {
    id: 18,
    firstName: "Ursulina",
    lastName: "Malyon",
    email: "umalyonh@facebook.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "2/5/2021",
    address1: "1623 Veith Pass",
    zipCode: "67260",
    city: "Wichita",
    state: "KS",
    fullName: "Ursulina Malyon",
  },
  {
    id: 19,
    firstName: "Wrennie",
    lastName: "Lambdean",
    email: "wlambdeani@intel.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "12/21/2020",
    address1: "615 Stone Corner Alley",
    zipCode: "99220",
    city: "Spokane",
    state: "WA",
    fullName: "Wrennie Lambdean",
  },
  {
    id: 20,
    firstName: "Bunni",
    lastName: "Haukey",
    email: "bhaukeyj@google.de",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "5/4/2021",
    address1: "8 Sundown Way",
    zipCode: "35285",
    city: "Birmingham",
    state: "AL",
    fullName: "Bunni Haukey",
  },
  {
    id: 21,
    firstName: "Gaby",
    lastName: "Dobkin",
    email: "gdobkink@google.fr",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "1/13/2021",
    address1: "64 Mitchell Street",
    zipCode: "72204",
    city: "Little Rock",
    state: "AR",
    fullName: "Gaby Dobkin",
  },
  {
    id: 22,
    firstName: "Cyndi",
    lastName: "Whitney",
    email: "cwhitneyl@reverbnation.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "4/23/2021",
    address1: "3 Grayhawk Court",
    zipCode: "92662",
    city: "Newport Beach",
    state: "CA",
    fullName: "Cyndi Whitney",
  },
  {
    id: 23,
    firstName: "Lindsy",
    lastName: "Talbot",
    email: "ltalbotm@bloglovin.com",
    clientType: "COMPANY",
    companyName: "King Group",
    dateCreated: "2/7/2021",
    address1: "9 Manitowish Hill",
    zipCode: "77035",
    city: "Houston",
    state: "TX",
    fullName: "Lindsy Talbot",
  },
  {
    id: 24,
    firstName: "Bobinette",
    lastName: "Bousler",
    email: "bbouslern@wufoo.com",
    clientType: "COMPANY",
    companyName: "MacGyver Inc",
    dateCreated: "1/11/2021",
    address1: "75798 Atwood Street",
    zipCode: "66667",
    city: "Topeka",
    state: "KS",
    fullName: "Bobinette Bousler",
  },
  {
    id: 25,
    firstName: "Lockwood",
    lastName: "Rowly",
    email: "lrowlyo@fastcompany.com",
    clientType: "COMPANY",
    companyName: "Fay Inc",
    dateCreated: "11/7/2020",
    address1: "357 Porter Terrace",
    zipCode: "40510",
    city: "Lexington",
    state: "KY",
    fullName: "Lockwood Rowly",
  },
  {
    id: 26,
    firstName: "Lizbeth",
    lastName: "McCurdy",
    email: "lmccurdyp@ted.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "9/28/2020",
    address1: "8242 Superior Alley",
    zipCode: "65805",
    city: "Springfield",
    state: "MO",
    fullName: "Lizbeth McCurdy",
  },
  {
    id: 27,
    firstName: "Pietro",
    lastName: "Sodory",
    email: "psodoryq@umn.edu",
    clientType: "COMPANY",
    companyName: "Bogan LLC",
    dateCreated: "2/17/2021",
    address1: "88 Gerald Court",
    zipCode: "94807",
    city: "Richmond",
    state: "CA",
    fullName: "Pietro Sodory",
  },
  {
    id: 28,
    firstName: "Angelia",
    lastName: "Sture",
    email: "asturer@psu.edu",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "6/24/2021",
    address1: "8316 Claremont Place",
    zipCode: "10004",
    city: "New York City",
    state: "NY",
    fullName: "Angelia Sture",
  },
  {
    id: 29,
    firstName: "Mason",
    lastName: "Merdew",
    email: "mmerdews@time.com",
    clientType: "COMPANY",
    companyName: "VonRueden LLC",
    dateCreated: "7/24/2021",
    address1: "86836 Kedzie Road",
    zipCode: "80241",
    city: "Denver",
    state: "CO",
    fullName: "Mason Merdew",
  },
  {
    id: 30,
    firstName: "Dannie",
    lastName: "Bellew",
    email: "dbellewt@ask.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "2/23/2021",
    address1: "97300 Dapin Lane",
    zipCode: "73197",
    city: "Oklahoma City",
    state: "OK",
    fullName: "Dannie Bellew",
  },
  {
    id: 31,
    firstName: "Herta",
    lastName: "Heenan",
    email: "hheenanu@guardian.co.uk",
    clientType: "COMPANY",
    companyName: "Wilderman and Sons",
    dateCreated: "6/8/2021",
    address1: "928 Mifflin Circle",
    zipCode: "30066",
    city: "Marietta",
    state: "GA",
    fullName: "Herta Heenan",
  },
  {
    id: 32,
    firstName: "Alexei",
    lastName: "Mouse",
    email: "amousev@webmd.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "10/4/2020",
    address1: "7 Green Ridge Park",
    zipCode: "23551",
    city: "Norfolk",
    state: "VA",
    fullName: "Alexei Mouse",
  },
  {
    id: 33,
    firstName: "Anallise",
    lastName: "Beckinsall",
    email: "abeckinsallw@abc.net.au",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "10/24/2020",
    address1: "891 Onsgard Parkway",
    zipCode: "40515",
    city: "Lexington",
    state: "KY",
    fullName: "Anallise Beckinsall",
  },
  {
    id: 34,
    firstName: "Yelena",
    lastName: "MacInherney",
    email: "ymacinherneyx@flickr.com",
    clientType: "COMPANY",
    companyName: "Schmitt, Schuppe and Roob",
    dateCreated: "10/14/2020",
    address1: "7556 Maywood Trail",
    zipCode: "78759",
    city: "Austin",
    state: "TX",
    fullName: "Yelena MacInherney",
  },
  {
    id: 35,
    firstName: "Cassie",
    lastName: "Gaitley",
    email: "cgaitleyy@noaa.gov",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "7/13/2021",
    address1: "79 Arizona Alley",
    zipCode: "95173",
    city: "San Jose",
    state: "CA",
    fullName: "Cassie Gaitley",
  },
  {
    id: 36,
    firstName: "Xylina",
    lastName: "Henningham",
    email: "xhenninghamz@weebly.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "7/30/2021",
    address1: "0 North Circle",
    zipCode: "06183",
    city: "Hartford",
    state: "CT",
    fullName: "Xylina Henningham",
  },
  {
    id: 37,
    firstName: "Marcello",
    lastName: "Hows",
    email: "mhows10@digg.com",
    clientType: "COMPANY",
    companyName: "Schimmel-Hauck",
    dateCreated: "1/23/2021",
    address1: "67 Superior Lane",
    zipCode: "98175",
    city: "Seattle",
    state: "WA",
    fullName: "Marcello Hows",
  },
  {
    id: 38,
    firstName: "Tymon",
    lastName: "Mizen",
    email: "tmizen11@smh.com.au",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "4/22/2021",
    address1: "5 Esker Center",
    zipCode: "95108",
    city: "San Jose",
    state: "CA",
    fullName: "Tymon Mizen",
  },
  {
    id: 39,
    firstName: "Austina",
    lastName: "Rentalll",
    email: "arentalll12@indiegogo.com",
    clientType: "COMPANY",
    companyName: "Leannon, Vandervort and Bergstrom",
    dateCreated: "12/8/2020",
    address1: "39383 Larry Plaza",
    zipCode: "48217",
    city: "Detroit",
    state: "MI",
    fullName: "Austina Rentalll",
  },
  {
    id: 40,
    firstName: "Allissa",
    lastName: "Malling",
    email: "amalling13@businessinsider.com",
    clientType: "COMPANY",
    companyName: "Parisian Group",
    dateCreated: "3/1/2021",
    address1: "7 Superior Alley",
    zipCode: "39505",
    city: "Gulfport",
    state: "MS",
    fullName: "Allissa Malling",
  },
  {
    id: 41,
    firstName: "Nicolai",
    lastName: "Kidder",
    email: "nkidder14@army.mil",
    clientType: "COMPANY",
    companyName: "Spinka-Miller",
    dateCreated: "1/4/2021",
    address1: "190 Corry Avenue",
    zipCode: "25721",
    city: "Huntington",
    state: "WV",
    fullName: "Nicolai Kidder",
  },
  {
    id: 42,
    firstName: "Jeannette",
    lastName: "Tofts",
    email: "jtofts15@bloomberg.com",
    clientType: "COMPANY",
    companyName: "Sanford Inc",
    dateCreated: "12/18/2020",
    address1: "2827 Burrows Terrace",
    zipCode: "33758",
    city: "Clearwater",
    state: "FL",
    fullName: "Jeannette Tofts",
  },
  {
    id: 43,
    firstName: "Elvin",
    lastName: "Fairburn",
    email: "efairburn16@123-reg.co.uk",
    clientType: "COMPANY",
    companyName: "Connelly, Sipes and Muller",
    dateCreated: "1/12/2021",
    address1: "32 Ilene Park",
    zipCode: "32092",
    city: "Saint Augustine",
    state: "FL",
    fullName: "Elvin Fairburn",
  },
  {
    id: 44,
    firstName: "Candide",
    lastName: "Pickett",
    email: "cpickett17@phoca.cz",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "2/6/2021",
    address1: "0 Drewry Terrace",
    zipCode: "91406",
    city: "Van Nuys",
    state: "CA",
    fullName: "Candide Pickett",
  },
  {
    id: 45,
    firstName: "Sheela",
    lastName: "Varnham",
    email: "svarnham18@pinterest.com",
    clientType: "COMPANY",
    companyName: "Ferry and Sons",
    dateCreated: "6/4/2021",
    address1: "1182 Waubesa Junction",
    zipCode: "33436",
    city: "Boynton Beach",
    state: "FL",
    fullName: "Sheela Varnham",
  },
  {
    id: 46,
    firstName: "Saundra",
    lastName: "Oddboy",
    email: "soddboy19@goodreads.com",
    clientType: "COMPANY",
    companyName: "Robel and Sons",
    dateCreated: "11/22/2020",
    address1: "106 Westend Way",
    zipCode: "43204",
    city: "Columbus",
    state: "OH",
    fullName: "Saundra Oddboy",
  },
  {
    id: 47,
    firstName: "Sully",
    lastName: "Casetta",
    email: "scasetta1a@yelp.com",
    clientType: "COMPANY",
    companyName: "Dickinson, Erdman and Kling",
    dateCreated: "6/26/2021",
    address1: "24199 Stephen Street",
    zipCode: "98447",
    city: "Tacoma",
    state: "WA",
    fullName: "Sully Casetta",
  },
  {
    id: 48,
    firstName: "Tracee",
    lastName: "Franz",
    email: "tfranz1b@pagesperso-orange.fr",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "9/6/2021",
    address1: "2 Cody Alley",
    zipCode: "36628",
    city: "Mobile",
    state: "AL",
    fullName: "Tracee Franz",
  },
  {
    id: 49,
    firstName: "Vinnie",
    lastName: "Finlaison",
    email: "vfinlaison1c@rediff.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "12/22/2020",
    address1: "619 Oneill Lane",
    zipCode: "93740",
    city: "Fresno",
    state: "CA",
    fullName: "Vinnie Finlaison",
  },
  {
    id: 50,
    firstName: "Barry",
    lastName: "Howle",
    email: "bhowle1d@slate.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "5/29/2021",
    address1: "8981 Declaration Junction",
    zipCode: "63150",
    city: "Saint Louis",
    state: "MO",
    fullName: "Barry Howle",
  },
  {
    id: 51,
    firstName: "Alric",
    lastName: "Skill",
    email: "askill1e@feedburner.com",
    clientType: "COMPANY",
    companyName: "Rau, Jaskolski and Hammes",
    dateCreated: "6/9/2021",
    address1: "9 Forest Run Point",
    zipCode: "32230",
    city: "Jacksonville",
    state: "FL",
    fullName: "Alric Skill",
  },
  {
    id: 52,
    firstName: "Hyatt",
    lastName: "Sharvill",
    email: "hsharvill1f@discuz.net",
    clientType: "COMPANY",
    companyName: "Reinger-Wunsch",
    dateCreated: "5/30/2021",
    address1: "84 Express Trail",
    zipCode: "98008",
    city: "Bellevue",
    state: "WA",
    fullName: "Hyatt Sharvill",
  },
  {
    id: 53,
    firstName: "Torrence",
    lastName: "Kob",
    email: "tkob1g@arizona.edu",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "12/9/2020",
    address1: "823 Sage Drive",
    zipCode: "10110",
    city: "New York City",
    state: "NY",
    fullName: "Torrence Kob",
  },
  {
    id: 54,
    firstName: "Claybourne",
    lastName: "Scogings",
    email: "cscogings1h@github.com",
    clientType: "COMPANY",
    companyName: "Pfeffer and Sons",
    dateCreated: "12/9/2020",
    address1: "3230 Lyons Parkway",
    zipCode: "89130",
    city: "Las Vegas",
    state: "NV",
    fullName: "Claybourne Scogings",
  },
  {
    id: 55,
    firstName: "Marj",
    lastName: "Germain",
    email: "mgermain1i@mit.edu",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "12/18/2020",
    address1: "219 Aberg Pass",
    zipCode: "03105",
    city: "Manchester",
    state: "NH",
    fullName: "Marj Germain",
  },
  {
    id: 56,
    firstName: "Jade",
    lastName: "Romand",
    email: "jromand1j@ebay.co.uk",
    clientType: "COMPANY",
    companyName: "Kshlerin, Ullrich and Fisher",
    dateCreated: "11/10/2020",
    address1: "03704 Pearson Street",
    zipCode: "59623",
    city: "Helena",
    state: "MT",
    fullName: "Jade Romand",
  },
  {
    id: 57,
    firstName: "Zonnya",
    lastName: "Germaine",
    email: "zgermaine1k@hhs.gov",
    clientType: "COMPANY",
    companyName: "Raynor and Sons",
    dateCreated: "12/12/2020",
    address1: "4884 Loomis Drive",
    zipCode: "77020",
    city: "Houston",
    state: "TX",
    fullName: "Zonnya Germaine",
  },
  {
    id: 58,
    firstName: "Salome",
    lastName: "Comsty",
    email: "scomsty1l@slideshare.net",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "2/5/2021",
    address1: "70100 Moose Lane",
    zipCode: "40256",
    city: "Louisville",
    state: "KY",
    fullName: "Salome Comsty",
  },
  {
    id: 59,
    firstName: "Culley",
    lastName: "Sibson",
    email: "csibson1m@weather.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "4/24/2021",
    address1: "26831 Warrior Street",
    zipCode: "06726",
    city: "Waterbury",
    state: "CT",
    fullName: "Culley Sibson",
  },
  {
    id: 60,
    firstName: "Danita",
    lastName: "Hartridge",
    email: "dhartridge1n@bloomberg.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "10/7/2020",
    address1: "14 Muir Lane",
    zipCode: "85067",
    city: "Phoenix",
    state: "AZ",
    fullName: "Danita Hartridge",
  },
  {
    id: 61,
    firstName: "Iris",
    lastName: "Roblou",
    email: "iroblou1o@google.es",
    clientType: "COMPANY",
    companyName: "White, Balistreri and Klein",
    dateCreated: "6/9/2021",
    address1: "8 Forest Run Hill",
    zipCode: "80328",
    city: "Boulder",
    state: "CO",
    fullName: "Iris Roblou",
  },
  {
    id: 62,
    firstName: "Cristi",
    lastName: "Barrowcliff",
    email: "cbarrowcliff1p@businesswire.com",
    clientType: "COMPANY",
    companyName: "Sporer, Johnston and Schulist",
    dateCreated: "11/10/2020",
    address1: "79 Duke Terrace",
    zipCode: "64504",
    city: "Saint Joseph",
    state: "MO",
    fullName: "Cristi Barrowcliff",
  },
  {
    id: 63,
    firstName: "Regine",
    lastName: "Mossbee",
    email: "rmossbee1q@msn.com",
    clientType: "COMPANY",
    companyName: "O'Connell-D'Amore",
    dateCreated: "12/19/2020",
    address1: "7580 Sutteridge Alley",
    zipCode: "92805",
    city: "Anaheim",
    state: "CA",
    fullName: "Regine Mossbee",
  },
  {
    id: 64,
    firstName: "Tamera",
    lastName: "Oppie",
    email: "toppie1r@auda.org.au",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "5/14/2021",
    address1: "7 Kinsman Street",
    zipCode: "87140",
    city: "Albuquerque",
    state: "NM",
    fullName: "Tamera Oppie",
  },
  {
    id: 65,
    firstName: "Theodor",
    lastName: "Abrey",
    email: "tabrey1s@arstechnica.com",
    clientType: "COMPANY",
    companyName: "Bayer, Jerde and Hamill",
    dateCreated: "3/14/2021",
    address1: "99 Thompson Road",
    zipCode: "79999",
    city: "El Paso",
    state: "TX",
    fullName: "Theodor Abrey",
  },
  {
    id: 66,
    firstName: "Lorin",
    lastName: "Scorthorne",
    email: "lscorthorne1t@foxnews.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "2/15/2021",
    address1: "4 Rutledge Junction",
    zipCode: "85297",
    city: "Gilbert",
    state: "AZ",
    fullName: "Lorin Scorthorne",
  },
  {
    id: 67,
    firstName: "Haley",
    lastName: "Aldiss",
    email: "haldiss1u@tiny.cc",
    clientType: "COMPANY",
    companyName: "Hintz, Pacocha and Tromp",
    dateCreated: "1/12/2021",
    address1: "346 Calypso Crossing",
    zipCode: "64125",
    city: "Kansas City",
    state: "MO",
    fullName: "Haley Aldiss",
  },
  {
    id: 68,
    firstName: "Helena",
    lastName: "Starsmeare",
    email: "hstarsmeare1v@vkontakte.ru",
    clientType: "COMPANY",
    companyName: "Daniel-Bosco",
    dateCreated: "3/7/2021",
    address1: "59 Linden Hill",
    zipCode: "27705",
    city: "Durham",
    state: "NC",
    fullName: "Helena Starsmeare",
  },
  {
    id: 69,
    firstName: "Emylee",
    lastName: "Oleszczak",
    email: "eoleszczak1w@csmonitor.com",
    clientType: "COMPANY",
    companyName: "Fisher Inc",
    dateCreated: "10/14/2020",
    address1: "2194 Blue Bill Park Park",
    zipCode: "28220",
    city: "Charlotte",
    state: "NC",
    fullName: "Emylee Oleszczak",
  },
  {
    id: 70,
    firstName: "Trisha",
    lastName: "Gavrieli",
    email: "tgavrieli1x@ftc.gov",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "8/26/2021",
    address1: "7148 Amoth Court",
    zipCode: "90610",
    city: "Whittier",
    state: "CA",
    fullName: "Trisha Gavrieli",
  },
  {
    id: 71,
    firstName: "Joelie",
    lastName: "Abba",
    email: "jabba1y@uol.com.br",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "7/19/2021",
    address1: "59 Loomis Plaza",
    zipCode: "91616",
    city: "North Hollywood",
    state: "CA",
    fullName: "Joelie Abba",
  },
  {
    id: 72,
    firstName: "Babara",
    lastName: "Hurdman",
    email: "bhurdman1z@timesonline.co.uk",
    clientType: "COMPANY",
    companyName: "Murray-King",
    dateCreated: "2/3/2021",
    address1: "335 Jay Pass",
    zipCode: "78255",
    city: "San Antonio",
    state: "TX",
    fullName: "Babara Hurdman",
  },
  {
    id: 73,
    firstName: "Mariya",
    lastName: "Enoksson",
    email: "menoksson20@wordpress.com",
    clientType: "COMPANY",
    companyName: "Berge-Kertzmann",
    dateCreated: "1/30/2021",
    address1: "8 Towne Pass",
    zipCode: "34605",
    city: "Brooksville",
    state: "FL",
    fullName: "Mariya Enoksson",
  },
  {
    id: 74,
    firstName: "Mari",
    lastName: "Grebbin",
    email: "mgrebbin21@boston.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "12/15/2020",
    address1: "64 Messerschmidt Plaza",
    zipCode: "07544",
    city: "Paterson",
    state: "NJ",
    fullName: "Mari Grebbin",
  },
  {
    id: 75,
    firstName: "Tomi",
    lastName: "Amis",
    email: "tamis22@nydailynews.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "9/29/2020",
    address1: "1846 Golf View Junction",
    zipCode: "90025",
    city: "Los Angeles",
    state: "CA",
    fullName: "Tomi Amis",
  },
  {
    id: 76,
    firstName: "Roseline",
    lastName: "Spoors",
    email: "rspoors23@webmd.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "1/9/2021",
    address1: "39 Roth Parkway",
    zipCode: "20067",
    city: "Washington",
    state: "DC",
    fullName: "Roseline Spoors",
  },
  {
    id: 77,
    firstName: "Lewes",
    lastName: "Redford",
    email: "lredford24@livejournal.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "7/16/2021",
    address1: "628 Northport Way",
    zipCode: "20397",
    city: "Washington",
    state: "DC",
    fullName: "Lewes Redford",
  },
  {
    id: 78,
    firstName: "Arel",
    lastName: "Crosse",
    email: "acrosse25@purevolume.com",
    clientType: "COMPANY",
    companyName: "Prohaska LLC",
    dateCreated: "8/28/2021",
    address1: "23 Tennyson Point",
    zipCode: "88530",
    city: "El Paso",
    state: "TX",
    fullName: "Arel Crosse",
  },
  {
    id: 79,
    firstName: "Sabina",
    lastName: "Guislin",
    email: "sguislin26@amazon.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "5/25/2021",
    address1: "33 Delaware Point",
    zipCode: "93305",
    city: "Bakersfield",
    state: "CA",
    fullName: "Sabina Guislin",
  },
  {
    id: 80,
    firstName: "Donny",
    lastName: "Adam",
    email: "dadam27@narod.ru",
    clientType: "COMPANY",
    companyName: "Kris-Feeney",
    dateCreated: "6/9/2021",
    address1: "3 Golf Course Lane",
    zipCode: "10474",
    city: "Bronx",
    state: "NY",
    fullName: "Donny Adam",
  },
  {
    id: 81,
    firstName: "Sadye",
    lastName: "Cannan",
    email: "scannan28@purevolume.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "3/12/2021",
    address1: "15121 Mayfield Way",
    zipCode: "27264",
    city: "High Point",
    state: "NC",
    fullName: "Sadye Cannan",
  },
  {
    id: 82,
    firstName: "Grissel",
    lastName: "Isherwood",
    email: "gisherwood29@vinaora.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "6/18/2021",
    address1: "0 Buell Trail",
    zipCode: "34290",
    city: "North Port",
    state: "FL",
    fullName: "Grissel Isherwood",
  },
  {
    id: 83,
    firstName: "Norean",
    lastName: "Wathen",
    email: "nwathen2a@smugmug.com",
    clientType: "COMPANY",
    companyName: "Tremblay, Pacocha and Kovacek",
    dateCreated: "9/13/2020",
    address1: "96 Monument Junction",
    zipCode: "15906",
    city: "Johnstown",
    state: "PA",
    fullName: "Norean Wathen",
  },
  {
    id: 84,
    firstName: "Jobina",
    lastName: "Rainforth",
    email: "jrainforth2b@canalblog.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "7/27/2021",
    address1: "8977 Valley Edge Hill",
    zipCode: "23285",
    city: "Richmond",
    state: "VA",
    fullName: "Jobina Rainforth",
  },
  {
    id: 85,
    firstName: "Ainslie",
    lastName: "Coffey",
    email: "acoffey2c@scribd.com",
    clientType: "COMPANY",
    companyName: "Brakus, Muller and Gislason",
    dateCreated: "3/11/2021",
    address1: "82461 Ridge Oak Alley",
    zipCode: "25770",
    city: "Huntington",
    state: "WV",
    fullName: "Ainslie Coffey",
  },
  {
    id: 86,
    firstName: "Erny",
    lastName: "McKinnell",
    email: "emckinnell2d@ow.ly",
    clientType: "COMPANY",
    companyName: "Dibbert-Tromp",
    dateCreated: "6/7/2021",
    address1: "95 Reinke Drive",
    zipCode: "06127",
    city: "West Hartford",
    state: "CT",
    fullName: "Erny McKinnell",
  },
  {
    id: 87,
    firstName: "Janella",
    lastName: "Kubatsch",
    email: "jkubatsch2e@angelfire.com",
    clientType: "COMPANY",
    companyName: "Dickinson, Schaefer and Pfannerstill",
    dateCreated: "2/12/2021",
    address1: "159 Duke Road",
    zipCode: "78265",
    city: "San Antonio",
    state: "TX",
    fullName: "Janella Kubatsch",
  },
  {
    id: 88,
    firstName: "Shem",
    lastName: "Spelling",
    email: "sspelling2f@japanpost.jp",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "1/23/2021",
    address1: "99 Westerfield Center",
    zipCode: "79118",
    city: "Amarillo",
    state: "TX",
    fullName: "Shem Spelling",
  },
  {
    id: 89,
    firstName: "Osbourne",
    lastName: "Janny",
    email: "ojanny2g@godaddy.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "9/27/2020",
    address1: "9296 Clove Crossing",
    zipCode: "47905",
    city: "Lafayette",
    state: "IN",
    fullName: "Osbourne Janny",
  },
  {
    id: 90,
    firstName: "Weider",
    lastName: "Paniman",
    email: "wpaniman2h@disqus.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "1/16/2021",
    address1: "0 Debra Place",
    zipCode: "01129",
    city: "Springfield",
    state: "MA",
    fullName: "Weider Paniman",
  },
  {
    id: 91,
    firstName: "Pandora",
    lastName: "Dyshart",
    email: "pdyshart2i@hao123.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "2/2/2021",
    address1: "2 Carey Alley",
    zipCode: "20591",
    city: "Washington",
    state: "DC",
    fullName: "Pandora Dyshart",
  },
  {
    id: 92,
    firstName: "Shay",
    lastName: "Danne",
    email: "sdanne2j@goo.gl",
    clientType: "COMPANY",
    companyName: "Anderson, Brakus and Nader",
    dateCreated: "10/22/2020",
    address1: "201 5th Court",
    zipCode: "60614",
    city: "Chicago",
    state: "IL",
    fullName: "Shay Danne",
  },
  {
    id: 93,
    firstName: "Aloise",
    lastName: "Bakewell",
    email: "abakewell2k@zimbio.com",
    clientType: "COMPANY",
    companyName: "Rosenbaum-Gottlieb",
    dateCreated: "7/20/2021",
    address1: "553 Farragut Pass",
    zipCode: "53785",
    city: "Madison",
    state: "WI",
    fullName: "Aloise Bakewell",
  },
  {
    id: 94,
    firstName: "Ilyse",
    lastName: "Kavanagh",
    email: "ikavanagh2l@japanpost.jp",
    clientType: "COMPANY",
    companyName: "Rohan, Rice and Douglas",
    dateCreated: "11/24/2020",
    address1: "6870 Lyons Trail",
    zipCode: "12247",
    city: "Albany",
    state: "NY",
    fullName: "Ilyse Kavanagh",
  },
  {
    id: 95,
    firstName: "Michelle",
    lastName: "Duckham",
    email: "mduckham2m@rambler.ru",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "8/8/2021",
    address1: "284 Northridge Pass",
    zipCode: "77201",
    city: "Houston",
    state: "TX",
    fullName: "Michelle Duckham",
  },
  {
    id: 96,
    firstName: "Scotty",
    lastName: "Geard",
    email: "sgeard2n@mtv.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "2/20/2021",
    address1: "509 Pond Pass",
    zipCode: "91841",
    city: "Alhambra",
    state: "CA",
    fullName: "Scotty Geard",
  },
  {
    id: 97,
    firstName: "Marsiella",
    lastName: "Mathevet",
    email: "mmathevet2o@gizmodo.com",
    clientType: "COMPANY",
    companyName: "Durgan Group",
    dateCreated: "9/3/2021",
    address1: "8 Linden Park",
    zipCode: "48901",
    city: "Lansing",
    state: "MI",
    fullName: "Marsiella Mathevet",
  },
  {
    id: 98,
    firstName: "Pace",
    lastName: "Hilbourne",
    email: "philbourne2p@techcrunch.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "5/9/2021",
    address1: "62 Redwing Place",
    zipCode: "88525",
    city: "El Paso",
    state: "TX",
    fullName: "Pace Hilbourne",
  },
  {
    id: 99,
    firstName: "Field",
    lastName: "Bevan",
    email: "fbevan2q@rambler.ru",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "4/15/2021",
    address1: "95 Mayer Lane",
    zipCode: "31196",
    city: "Atlanta",
    state: "GA",
    fullName: "Field Bevan",
  },
  {
    id: 100,
    firstName: "Bertine",
    lastName: "Dunphie",
    email: "bdunphie2r@homestead.com",
    clientType: "INDIVIDUAL",
    companyName: null,
    dateCreated: "8/2/2021",
    address1: "95151 Mallard Hill",
    zipCode: "20268",
    city: "Washington",
    state: "DC",
    fullName: "Bertine Dunphie",
  },
];

Promise.all(clients.map((c) => addClients(c, { user: { id: 2 } }))).then(
  (values) => (process.exitCode = 1)
);
