import React, { useState, useEffect, useRef } from "react";
import { useRouter } from "./../../hooks/useRouter";
import { ClientService } from "./../../services/client-service";
import PlusSvg from "./../../components/icons/PlusSvg";
import { ClientsTable } from "./../../components/ClientsTable";
import styles from "./styles.module.css";
import { Button } from "./../../components/Button";
import { Pagination } from "./../../components/Pagination";

const SORT_BY_ASCENDING = "sortByAsc";
const SORT_BY_DESCENDING = "sortByDesc";
const SHOW_ALL = "all";
const SEARCH = "search";

const LIMIT = 15;

/* use debounce when searching */

export default function ClientsPage() {
  const [clients, setClients] = useState(getClientList());
  const [mode, setMode] = useState(SHOW_ALL);
  const [sortBy, setSortBy] = useState({ sort: "first_name,last_name" });
  const [page, setPage] = useState(1);
  const [pages, setPages] = useState(1);
  const [searchTerm, setSearchTerm] = useState("");

  const { push } = useRouter();

  useEffect(function () {
    fetchClients()
      .then((results) => {
        setPages(results.pageCount);
        setClients(results.clients);
      })
      .catch((error) => console.log(error));
  }, []);

  useEffect(
    function () {
      setMode(SEARCH);
    },
    [searchTerm]
  );

  useEffect(
    function () {
      setPage(1);
    },
    [mode]
  );

  useEffect(
    function () {
      fetchClients()
        .then((results) => {
          setPages(results.pageCount);
          setClients(results.clients);
        })
        .catch((error) => console.log(error));
    },
    [mode, sortBy, page, searchTerm]
  );

  function incrementPage() {
    setPage(page + 1);
  }

  function decrementPage() {
    setPage(page - 1);
  }

  function sortAscending(fields) {
    setMode(SORT_BY_ASCENDING);
    setSortBy({ sort: fields });
  }

  function sortDescending(fields) {
    setMode(SORT_BY_DESCENDING);
    setSortBy({ sort: `-${fields}` });
  }

  // function filterOnName(e) {
  //   console.log(e);

  //   if (e.key === "Shift") return;
  //   if (e.key === "Alt") return;
  //   if (e.key === "Control") return;
  //   console.log("pass");
  //   setSearchTerm(() => e.target.value);
  //   setMode(SEARCH);
  // }

  async function fetchClients() {
    let clients;

    switch (mode) {
      case SHOW_ALL: {
        clients = await ClientService.getClients({
          ...sortBy,
          ...{ limit: LIMIT, offset: (page - 1) * LIMIT },
        });
        break;
      }
      case SORT_BY_ASCENDING: {
        clients = await ClientService.getClients({
          ...sortBy,
          ...{ limit: LIMIT, offset: (page - 1) * LIMIT },
        });
        break;
      }
      case SORT_BY_DESCENDING: {
        clients = await ClientService.getClients({
          ...sortBy,
          ...{ limit: LIMIT, offset: (page - 1) * LIMIT },
        });
        break;
      }
      case SEARCH: {
        clients = await ClientService.getClientsBySearchTerm({
          q: searchTerm,
          ...{ limit: LIMIT, offset: (page - 1) * LIMIT },
          ...sortBy,
        });
        break;
      }
      default: {
        throw Error("Invalid mode selected");
      }
    }

    return clients;
  }

  return (
    <main>
      <section className={styles.header}>
        <h2 className={styles.heading}>Clients</h2>
        <div>
          <button
            onClick={() => push("/client/new")}
            className={styles.addClientButton}
          >
            <PlusSvg className={styles.plusSvg}></PlusSvg>Add Client
          </button>
        </div>
      </section>
      <section>
        <div className={styles.tableControls}>
          <div>
            <input
              type="text"
              placeholder="Search by name"
              onChange={(e) => setSearchTerm(e.target.value)}
              value={searchTerm}
            ></input>
          </div>
          <div>
            <Button text="Filters" />
          </div>
        </div>
        <ClientsTable
          clients={clients.slice(0, 15)}
          actions={{ sortAscending, sortDescending }}
        />
        {/* <ClientsTablePagination currentPage={1} pages={10} /> */}
        <Pagination
          currentPage={page}
          pages={pages}
          incrementPage={incrementPage}
          decrementPage={decrementPage}
        />
      </section>
    </main>
  );
}

function getClientList() {
  return [
    {
      id: 1,
      firstName: "Karoly",
      lastName: "Chinn",
      email: "kchinn0@ustream.tv",
      companyName: "Dickinson-Cassin",
      clientType: "COMPANY",
      dateCreated: "6/29/2021",
      address1: "1610 Sherman Alley",
      zipCode: "29615",
      city: "Greenville",
      state: "SC",
    },
    {
      id: 2,
      firstName: "Vanna",
      lastName: "Sherston",
      email: "vsherston1@sitemeter.com",
      companyName: "Fadel, Pacocha and Ernser",
      clientType: "COMPANY",
      dateCreated: "5/28/2021",
      address1: "8627 Westport Place",
      zipCode: "10474",
      city: "Bronx",
      state: "NY",
    },
    {
      id: 3,
      firstName: "Tam",
      lastName: "McMylor",
      email: "tmcmylor2@omniture.com",
      companyName: "Sauer-Bode",
      clientType: "INDIVIDUAL",
      dateCreated: "11/10/2020",
      address1: "4026 Monterey Pass",
      zipCode: "33633",
      city: "Tampa",
      state: "FL",
    },
    {
      id: 4,
      firstName: "Oriana",
      lastName: "Loadman",
      email: "oloadman3@china.com.cn",
      companyName: "Walter-Doyle",
      clientType: "COMPANY",
      dateCreated: "3/31/2021",
      address1: "42 Prentice Point",
      zipCode: "27717",
      city: "Durham",
      state: "NC",
    },
    {
      id: 5,
      firstName: "Holli",
      lastName: "Florez",
      email: "hflorez4@illinois.edu",
      companyName: "Ferry-Rosenbaum",
      clientType: "INDIVIDUAL",
      dateCreated: "2/5/2021",
      address1: "652 Arrowood Road",
      zipCode: "78732",
      city: "Austin",
      state: "TX",
    },
    {
      id: 6,
      firstName: "Everard",
      lastName: "Delnevo",
      email: "edelnevo5@google.fr",
      companyName: "Strosin, Hammes and Cormier",
      clientType: "COMPANY",
      dateCreated: "3/19/2021",
      address1: "722 Vernon Lane",
      zipCode: "97211",
      city: "Portland",
      state: "OR",
    },
    {
      id: 7,
      firstName: "Agathe",
      lastName: "Folbige",
      email: "afolbige6@jalbum.net",
      companyName: "Dooley, Kunze and Lowe",
      clientType: "INDIVIDUAL",
      dateCreated: "6/13/2021",
      address1: "5223 Kings Avenue",
      zipCode: "48232",
      city: "Detroit",
      state: "MI",
    },
    {
      id: 8,
      firstName: "Munroe",
      lastName: "Atto",
      email: "matto7@ocn.ne.jp",
      companyName: "Cremin and Sons",
      clientType: "COMPANY",
      dateCreated: "9/2/2021",
      address1: "0978 Mandrake Place",
      zipCode: "73114",
      city: "Oklahoma City",
      state: "OK",
    },
    {
      id: 9,
      firstName: "Lotta",
      lastName: "Lydiatt",
      email: "llydiatt8@gizmodo.com",
      companyName: "Kertzmann-Bashirian",
      clientType: "COMPANY",
      dateCreated: "2/2/2021",
      address1: "8 Dottie Junction",
      zipCode: "80270",
      city: "Denver",
      state: "CO",
    },
    {
      id: 10,
      firstName: "Lynn",
      lastName: "Cantera",
      email: "lcantera9@answers.com",
      companyName: "Harvey Group",
      clientType: "COMPANY",
      dateCreated: "4/5/2021",
      address1: "1834 Ridgeview Park",
      zipCode: "48919",
      city: "Lansing",
      state: "MI",
    },
    {
      id: 11,
      firstName: "Brandais",
      lastName: "Ganniclifft",
      email: "bgannicliffta@gnu.org",
      companyName: "Turcotte LLC",
      clientType: "INDIVIDUAL",
      dateCreated: "1/5/2021",
      address1: "28939 Onsgard Parkway",
      zipCode: "95113",
      city: "San Jose",
      state: "CA",
    },
    {
      id: 12,
      firstName: "Barbette",
      lastName: "Dalziel",
      email: "bdalzielb@shutterfly.com",
      companyName: "Gislason, Swaniawski and Raynor",
      clientType: "INDIVIDUAL",
      dateCreated: "5/24/2021",
      address1: "82045 Russell Center",
      zipCode: "32118",
      city: "Daytona Beach",
      state: "FL",
    },
    {
      id: 13,
      firstName: "Denys",
      lastName: "Frances",
      email: "dfrancesc@t-online.de",
      companyName: "Ward, Crooks and Hagenes",
      clientType: "INDIVIDUAL",
      dateCreated: "5/18/2021",
      address1: "9 Bowman Alley",
      zipCode: "20062",
      city: "Washington",
      state: "DC",
    },
    {
      id: 14,
      firstName: "Sheff",
      lastName: "Remnant",
      email: "sremnantd@census.gov",
      companyName: "Senger Group",
      clientType: "COMPANY",
      dateCreated: "11/26/2020",
      address1: "5 Twin Pines Center",
      zipCode: "92645",
      city: "Garden Grove",
      state: "CA",
    },
    {
      id: 15,
      firstName: "Rickie",
      lastName: "Gudgeon",
      email: "rgudgeone@fastcompany.com",
      companyName: "Gibson Inc",
      clientType: "INDIVIDUAL",
      dateCreated: "12/30/2020",
      address1: "7 Towne Park",
      zipCode: "85725",
      city: "Tucson",
      state: "AZ",
    },
    {
      id: 16,
      firstName: "Una",
      lastName: "Treversh",
      email: "utrevershf@si.edu",
      companyName: "Spencer, Hilll and Rau",
      clientType: "COMPANY",
      dateCreated: "10/16/2020",
      address1: "55464 Mosinee Point",
      zipCode: "80328",
      city: "Boulder",
      state: "CO",
    },
    {
      id: 17,
      firstName: "Rori",
      lastName: "Zanetto",
      email: "rzanettog@amazonaws.com",
      companyName: "Jacobs-Bode",
      clientType: "INDIVIDUAL",
      dateCreated: "5/17/2021",
      address1: "72585 Harper Street",
      zipCode: "21405",
      city: "Annapolis",
      state: "MD",
    },
    {
      id: 18,
      firstName: "Billie",
      lastName: "Osinin",
      email: "bosininh@reference.com",
      companyName: "Friesen-Wehner",
      clientType: "COMPANY",
      dateCreated: "6/6/2021",
      address1: "25356 Maple Circle",
      zipCode: "55598",
      city: "Loretto",
      state: "MN",
    },
    {
      id: 19,
      firstName: "Amber",
      lastName: "Bierman",
      email: "abiermani@elegantthemes.com",
      companyName: "Armstrong Inc",
      clientType: "COMPANY",
      dateCreated: "5/18/2021",
      address1: "069 Fairview Drive",
      zipCode: "33345",
      city: "Fort Lauderdale",
      state: "FL",
    },
    {
      id: 20,
      firstName: "Mireielle",
      lastName: "Rizzillo",
      email: "mrizzilloj@wikipedia.org",
      companyName: "Anderson, Schaefer and Predovic",
      clientType: "INDIVIDUAL",
      dateCreated: "9/3/2021",
      address1: "0 Karstens Junction",
      zipCode: "46699",
      city: "South Bend",
      state: "IN",
    },
    {
      id: 21,
      firstName: "Arleen",
      lastName: "Gearing",
      email: "agearingk@msu.edu",
      companyName: "Hoeger-Gorczany",
      clientType: "INDIVIDUAL",
      dateCreated: "3/27/2021",
      address1: "04 Cambridge Court",
      zipCode: "94280",
      city: "Sacramento",
      state: "CA",
    },
    {
      id: 22,
      firstName: "Sashenka",
      lastName: "Acutt",
      email: "sacuttl@ebay.com",
      companyName: "Johnston, Wuckert and Cremin",
      clientType: "COMPANY",
      dateCreated: "12/19/2020",
      address1: "8418 Clove Place",
      zipCode: "57110",
      city: "Sioux Falls",
      state: "SD",
    },
    {
      id: 23,
      firstName: "Nicolais",
      lastName: "Caisley",
      email: "ncaisleym@jiathis.com",
      companyName: "Beahan-Pfeffer",
      clientType: "COMPANY",
      dateCreated: "1/21/2021",
      address1: "3028 Troy Lane",
      zipCode: "64149",
      city: "Kansas City",
      state: "MO",
    },
    {
      id: 24,
      firstName: "Lawton",
      lastName: "Cowdry",
      email: "lcowdryn@elpais.com",
      companyName: "Gleason-Swift",
      clientType: "INDIVIDUAL",
      dateCreated: "12/17/2020",
      address1: "0 Granby Lane",
      zipCode: "15205",
      city: "Pittsburgh",
      state: "PA",
    },
    {
      id: 25,
      firstName: "Fayette",
      lastName: "Reijmers",
      email: "freijmerso@moonfruit.com",
      companyName: "Ruecker-Lehner",
      clientType: "COMPANY",
      dateCreated: "9/26/2020",
      address1: "3 Sutherland Plaza",
      zipCode: "40524",
      city: "Lexington",
      state: "KY",
    },
    {
      id: 26,
      firstName: "Lucho",
      lastName: "Chamney",
      email: "lchamneyp@seattletimes.com",
      companyName: "Hirthe-Turcotte",
      clientType: "INDIVIDUAL",
      dateCreated: "8/15/2021",
      address1: "2 Pleasure Plaza",
      zipCode: "40205",
      city: "Louisville",
      state: "KY",
    },
    {
      id: 27,
      firstName: "Sindee",
      lastName: "Semper",
      email: "ssemperq@miibeian.gov.cn",
      companyName: "Cronin-Kerluke",
      clientType: "INDIVIDUAL",
      dateCreated: "4/5/2021",
      address1: "3 Oak Valley Crossing",
      zipCode: "22036",
      city: "Fairfax",
      state: "VA",
    },
    {
      id: 28,
      firstName: "Mort",
      lastName: "Nurse",
      email: "mnurser@xrea.com",
      companyName: "Bernhard-Hoeger",
      clientType: "INDIVIDUAL",
      dateCreated: "12/6/2020",
      address1: "7916 Fulton Trail",
      zipCode: "76016",
      city: "Arlington",
      state: "TX",
    },
    {
      id: 29,
      firstName: "Dianna",
      lastName: "Elger",
      email: "delgers@geocities.jp",
      companyName: "Turner LLC",
      clientType: "COMPANY",
      dateCreated: "7/9/2021",
      address1: "9841 Dahle Place",
      zipCode: "93794",
      city: "Fresno",
      state: "CA",
    },
    {
      id: 30,
      firstName: "Alli",
      lastName: "Pennyman",
      email: "apennymant@pinterest.com",
      companyName: "Schaden-Ward",
      clientType: "INDIVIDUAL",
      dateCreated: "10/28/2020",
      address1: "1 Moulton Hill",
      zipCode: "22093",
      city: "Ashburn",
      state: "VA",
    },
    {
      id: 31,
      firstName: "Brett",
      lastName: "Yitzhak",
      email: "byitzhaku@china.com.cn",
      companyName: "Batz-Smith",
      clientType: "COMPANY",
      dateCreated: "12/28/2020",
      address1: "16786 Holy Cross Center",
      zipCode: "46221",
      city: "Indianapolis",
      state: "IN",
    },
    {
      id: 32,
      firstName: "Jeni",
      lastName: "Iannetti",
      email: "jiannettiv@instagram.com",
      companyName: "Howell-Satterfield",
      clientType: "COMPANY",
      dateCreated: "11/5/2020",
      address1: "919 Trailsway Way",
      zipCode: "48505",
      city: "Flint",
      state: "MI",
    },
    {
      id: 33,
      firstName: "Mead",
      lastName: "Goundrill",
      email: "mgoundrillw@ycombinator.com",
      companyName: "Kerluke, Trantow and Lang",
      clientType: "COMPANY",
      dateCreated: "3/20/2021",
      address1: "054 Garrison Place",
      zipCode: "43240",
      city: "Columbus",
      state: "OH",
    },
    {
      id: 34,
      firstName: "Zia",
      lastName: "Mozzi",
      email: "zmozzix@admin.ch",
      companyName: "Pagac-Runolfsdottir",
      clientType: "INDIVIDUAL",
      dateCreated: "4/4/2021",
      address1: "72 Village Crossing",
      zipCode: "97229",
      city: "Portland",
      state: "OR",
    },
    {
      id: 35,
      firstName: "Una",
      lastName: "Desmond",
      email: "udesmondy@timesonline.co.uk",
      companyName: "Boyer, Douglas and Turcotte",
      clientType: "INDIVIDUAL",
      dateCreated: "5/23/2021",
      address1: "6772 South Circle",
      zipCode: "06825",
      city: "Fairfield",
      state: "CT",
    },
    {
      id: 36,
      firstName: "Rona",
      lastName: "Duddle",
      email: "rduddlez@com.com",
      companyName: "Morar-Haley",
      clientType: "COMPANY",
      dateCreated: "12/23/2020",
      address1: "30 Clove Avenue",
      zipCode: "49560",
      city: "Grand Rapids",
      state: "MI",
    },
    {
      id: 37,
      firstName: "Jermayne",
      lastName: "Kid",
      email: "jkid10@miitbeian.gov.cn",
      companyName: "Bruen, Schroeder and Wolf",
      clientType: "INDIVIDUAL",
      dateCreated: "3/28/2021",
      address1: "827 Mitchell Circle",
      zipCode: "78789",
      city: "Austin",
      state: "TX",
    },
    {
      id: 38,
      firstName: "Chere",
      lastName: "Dalling",
      email: "cdalling11@issuu.com",
      companyName: "Kunze-Kassulke",
      clientType: "INDIVIDUAL",
      dateCreated: "1/4/2021",
      address1: "19255 Independence Point",
      zipCode: "33023",
      city: "Hollywood",
      state: "FL",
    },
    {
      id: 39,
      firstName: "Brice",
      lastName: "Costin",
      email: "bcostin12@lycos.com",
      companyName: "Smith, Kemmer and Orn",
      clientType: "COMPANY",
      dateCreated: "7/19/2021",
      address1: "0 Hoepker Circle",
      zipCode: "93591",
      city: "Palmdale",
      state: "CA",
    },
    {
      id: 40,
      firstName: "Ruth",
      lastName: "Pavlata",
      email: "rpavlata13@blinklist.com",
      companyName: "Davis, Cronin and Blick",
      clientType: "COMPANY",
      dateCreated: "4/29/2021",
      address1: "11433 Donald Crossing",
      zipCode: "39296",
      city: "Jackson",
      state: "MS",
    },
    {
      id: 41,
      firstName: "Dinah",
      lastName: "Searby",
      email: "dsearby14@360.cn",
      companyName: "Kirlin LLC",
      clientType: "COMPANY",
      dateCreated: "4/2/2021",
      address1: "37 Summerview Place",
      zipCode: "33153",
      city: "Miami",
      state: "FL",
    },
    {
      id: 42,
      firstName: "Dania",
      lastName: "Leavens",
      email: "dleavens15@usnews.com",
      companyName: "Hagenes, Ondricka and Marks",
      clientType: "INDIVIDUAL",
      dateCreated: "10/31/2020",
      address1: "2877 Pepper Wood Trail",
      zipCode: "85020",
      city: "Phoenix",
      state: "AZ",
    },
    {
      id: 43,
      firstName: "Rosemary",
      lastName: "Lile",
      email: "rlile16@nps.gov",
      companyName: "Strosin LLC",
      clientType: "COMPANY",
      dateCreated: "8/12/2021",
      address1: "2 Maple Way",
      zipCode: "32520",
      city: "Pensacola",
      state: "FL",
    },
    {
      id: 44,
      firstName: "Timoteo",
      lastName: "Casone",
      email: "tcasone17@npr.org",
      companyName: "Abernathy-Goodwin",
      clientType: "COMPANY",
      dateCreated: "3/11/2021",
      address1: "99298 Delaware Parkway",
      zipCode: "75397",
      city: "Dallas",
      state: "TX",
    },
    {
      id: 45,
      firstName: "Hall",
      lastName: "Stacy",
      email: "hstacy18@alibaba.com",
      companyName: "Murazik-Morar",
      clientType: "COMPANY",
      dateCreated: "4/3/2021",
      address1: "1 Pankratz Parkway",
      zipCode: "94230",
      city: "Sacramento",
      state: "CA",
    },
    {
      id: 46,
      firstName: "Kathlin",
      lastName: "Yanov",
      email: "kyanov19@geocities.jp",
      companyName: "Fisher-Purdy",
      clientType: "COMPANY",
      dateCreated: "1/7/2021",
      address1: "8 Erie Center",
      zipCode: "17105",
      city: "Harrisburg",
      state: "PA",
    },
    {
      id: 47,
      firstName: "Ynez",
      lastName: "Atte-Stone",
      email: "yattestone1a@booking.com",
      companyName: "Kirlin, Quigley and Gottlieb",
      clientType: "COMPANY",
      dateCreated: "12/1/2020",
      address1: "097 Warrior Street",
      zipCode: "79928",
      city: "El Paso",
      state: "TX",
    },
    {
      id: 48,
      firstName: "Juliann",
      lastName: "O'Corrin",
      email: "jocorrin1b@cornell.edu",
      companyName: "Anderson LLC",
      clientType: "INDIVIDUAL",
      dateCreated: "9/2/2021",
      address1: "402 Manufacturers Park",
      zipCode: "94116",
      city: "San Francisco",
      state: "CA",
    },
    {
      id: 49,
      firstName: "Petronella",
      lastName: "Spohr",
      email: "pspohr1c@gov.uk",
      companyName: "Kassulke Inc",
      clientType: "INDIVIDUAL",
      dateCreated: "8/10/2021",
      address1: "42282 Continental Park",
      zipCode: "78225",
      city: "San Antonio",
      state: "TX",
    },
    {
      id: 50,
      firstName: "Jeniece",
      lastName: "Allflatt",
      email: "jallflatt1d@un.org",
      companyName: "Fay, O'Conner and Wiegand",
      clientType: "INDIVIDUAL",
      dateCreated: "2/12/2021",
      address1: "5 Comanche Hill",
      zipCode: "14683",
      city: "Rochester",
      state: "NY",
    },
    {
      id: 51,
      firstName: "Sibella",
      lastName: "Linden",
      email: "slinden1e@hhs.gov",
      companyName: "Nitzsche, Treutel and Bartell",
      clientType: "COMPANY",
      dateCreated: "6/22/2021",
      address1: "095 Melby Center",
      zipCode: "89160",
      city: "Las Vegas",
      state: "NV",
    },
    {
      id: 52,
      firstName: "Andee",
      lastName: "Khidr",
      email: "akhidr1f@domainmarket.com",
      companyName: "McClure, Marvin and Auer",
      clientType: "COMPANY",
      dateCreated: "4/30/2021",
      address1: "5 Carberry Road",
      zipCode: "92030",
      city: "Escondido",
      state: "CA",
    },
    {
      id: 53,
      firstName: "Cully",
      lastName: "Simounet",
      email: "csimounet1g@mozilla.com",
      companyName: "Runolfsdottir-Zemlak",
      clientType: "INDIVIDUAL",
      dateCreated: "7/7/2021",
      address1: "1 Derek Park",
      zipCode: "46857",
      city: "Fort Wayne",
      state: "IN",
    },
    {
      id: 54,
      firstName: "Leonid",
      lastName: "Gresley",
      email: "lgresley1h@t.co",
      companyName: "Hagenes, Stokes and Purdy",
      clientType: "COMPANY",
      dateCreated: "12/29/2020",
      address1: "6019 Superior Junction",
      zipCode: "30089",
      city: "Decatur",
      state: "GA",
    },
    {
      id: 55,
      firstName: "Babara",
      lastName: "Lissaman",
      email: "blissaman1i@cpanel.net",
      companyName: "Jacobson-Walsh",
      clientType: "COMPANY",
      dateCreated: "6/16/2021",
      address1: "2 Coleman Alley",
      zipCode: "70883",
      city: "Baton Rouge",
      state: "LA",
    },
    {
      id: 56,
      firstName: "Ernst",
      lastName: "Krebs",
      email: "ekrebs1j@accuweather.com",
      companyName: "Zulauf, Rosenbaum and Johns",
      clientType: "COMPANY",
      dateCreated: "7/10/2021",
      address1: "8 Hooker Trail",
      zipCode: "77266",
      city: "Houston",
      state: "TX",
    },
    {
      id: 57,
      firstName: "Anselm",
      lastName: "Bertlin",
      email: "abertlin1k@csmonitor.com",
      companyName: "Zieme Inc",
      clientType: "INDIVIDUAL",
      dateCreated: "3/2/2021",
      address1: "4757 Dryden Lane",
      zipCode: "80243",
      city: "Denver",
      state: "CO",
    },
    {
      id: 58,
      firstName: "Errol",
      lastName: "Morican",
      email: "emorican1l@slate.com",
      companyName: "Rolfson, Labadie and Thompson",
      clientType: "COMPANY",
      dateCreated: "1/3/2021",
      address1: "16126 Grasskamp Pass",
      zipCode: "84140",
      city: "Salt Lake City",
      state: "UT",
    },
    {
      id: 59,
      firstName: "Earlie",
      lastName: "McGrah",
      email: "emcgrah1m@irs.gov",
      companyName: "Heathcote-Cole",
      clientType: "COMPANY",
      dateCreated: "6/26/2021",
      address1: "361 Lakewood Gardens Lane",
      zipCode: "68144",
      city: "Omaha",
      state: "NE",
    },
    {
      id: 60,
      firstName: "Laina",
      lastName: "Gettone",
      email: "lgettone1n@networkadvertising.org",
      companyName: "Predovic, Kertzmann and Bode",
      clientType: "COMPANY",
      dateCreated: "9/29/2020",
      address1: "1 Mockingbird Hill",
      zipCode: "32590",
      city: "Pensacola",
      state: "FL",
    },
    {
      id: 61,
      firstName: "Bambi",
      lastName: "Winsiowiecki",
      email: "bwinsiowiecki1o@newsvine.com",
      companyName: "Mayer and Sons",
      clientType: "COMPANY",
      dateCreated: "9/3/2021",
      address1: "107 Barby Point",
      zipCode: "75265",
      city: "Dallas",
      state: "TX",
    },
    {
      id: 62,
      firstName: "Lavinia",
      lastName: "Clemenceau",
      email: "lclemenceau1p@flickr.com",
      companyName: "Kertzmann Inc",
      clientType: "INDIVIDUAL",
      dateCreated: "2/2/2021",
      address1: "94222 Sutteridge Court",
      zipCode: "01129",
      city: "Springfield",
      state: "MA",
    },
    {
      id: 63,
      firstName: "Fax",
      lastName: "Gaynor",
      email: "fgaynor1q@addthis.com",
      companyName: "Cruickshank Inc",
      clientType: "COMPANY",
      dateCreated: "7/13/2021",
      address1: "7 Stoughton Avenue",
      zipCode: "46266",
      city: "Indianapolis",
      state: "IN",
    },
    {
      id: 64,
      firstName: "Caddric",
      lastName: "Hadcroft",
      email: "chadcroft1r@tamu.edu",
      companyName: "Hettinger, Strosin and Kuhic",
      clientType: "INDIVIDUAL",
      dateCreated: "5/17/2021",
      address1: "97 Carey Junction",
      zipCode: "93311",
      city: "Bakersfield",
      state: "CA",
    },
    {
      id: 65,
      firstName: "Lorry",
      lastName: "Keri",
      email: "lkeri1s@com.com",
      companyName: "Reichert-Ruecker",
      clientType: "INDIVIDUAL",
      dateCreated: "11/11/2020",
      address1: "10821 Ludington Parkway",
      zipCode: "79968",
      city: "El Paso",
      state: "TX",
    },
    {
      id: 66,
      firstName: "Dayle",
      lastName: "Michele",
      email: "dmichele1t@squidoo.com",
      companyName: "Monahan, Deckow and Schmitt",
      clientType: "INDIVIDUAL",
      dateCreated: "4/26/2021",
      address1: "40482 Ridge Oak Drive",
      zipCode: "79911",
      city: "El Paso",
      state: "TX",
    },
    {
      id: 67,
      firstName: "Demetri",
      lastName: "Virgo",
      email: "dvirgo1u@fema.gov",
      companyName: "Emard, Hayes and Hoeger",
      clientType: "COMPANY",
      dateCreated: "5/27/2021",
      address1: "00023 Linden Center",
      zipCode: "78426",
      city: "Corpus Christi",
      state: "TX",
    },
    {
      id: 68,
      firstName: "Hinze",
      lastName: "Raubheim",
      email: "hraubheim1v@redcross.org",
      companyName: "O'Kon, Kessler and Lesch",
      clientType: "INDIVIDUAL",
      dateCreated: "7/14/2021",
      address1: "80 Macpherson Junction",
      zipCode: "11431",
      city: "Jamaica",
      state: "NY",
    },
    {
      id: 69,
      firstName: "Evita",
      lastName: "Stag",
      email: "estag1w@cocolog-nifty.com",
      companyName: "Abshire-Bayer",
      clientType: "COMPANY",
      dateCreated: "4/6/2021",
      address1: "44026 Anniversary Park",
      zipCode: "49560",
      city: "Grand Rapids",
      state: "MI",
    },
    {
      id: 70,
      firstName: "Wendell",
      lastName: "Espinet",
      email: "wespinet1x@yale.edu",
      companyName: "Hammes-Oberbrunner",
      clientType: "COMPANY",
      dateCreated: "1/22/2021",
      address1: "216 Center Avenue",
      zipCode: "20016",
      city: "Washington",
      state: "DC",
    },
    {
      id: 71,
      firstName: "Rabbi",
      lastName: "Pauletto",
      email: "rpauletto1y@google.com.hk",
      companyName: "Beatty, Reilly and Mueller",
      clientType: "INDIVIDUAL",
      dateCreated: "10/7/2020",
      address1: "58 7th Court",
      zipCode: "89130",
      city: "Las Vegas",
      state: "NV",
    },
    {
      id: 72,
      firstName: "Amery",
      lastName: "Denington",
      email: "adenington1z@answers.com",
      companyName: "Johns-Corwin",
      clientType: "COMPANY",
      dateCreated: "8/8/2021",
      address1: "17935 Straubel Pass",
      zipCode: "92410",
      city: "San Bernardino",
      state: "CA",
    },
    {
      id: 73,
      firstName: "Launce",
      lastName: "Rourke",
      email: "lrourke20@java.com",
      companyName: "Kilback Group",
      clientType: "INDIVIDUAL",
      dateCreated: "4/15/2021",
      address1: "690 Carey Avenue",
      zipCode: "37228",
      city: "Nashville",
      state: "TN",
    },
    {
      id: 74,
      firstName: "Anna-diana",
      lastName: "Stillman",
      email: "astillman21@elpais.com",
      companyName: "Rempel, Von and Cormier",
      clientType: "COMPANY",
      dateCreated: "11/23/2020",
      address1: "1906 Washington Road",
      zipCode: "89115",
      city: "Las Vegas",
      state: "NV",
    },
    {
      id: 75,
      firstName: "Melany",
      lastName: "Spurdens",
      email: "mspurdens22@mozilla.org",
      companyName: "Oberbrunner Group",
      clientType: "INDIVIDUAL",
      dateCreated: "11/23/2020",
      address1: "929 Clove Drive",
      zipCode: "23514",
      city: "Norfolk",
      state: "VA",
    },
    {
      id: 76,
      firstName: "Isadora",
      lastName: "Sher",
      email: "isher23@imdb.com",
      companyName: "Murazik-Heidenreich",
      clientType: "INDIVIDUAL",
      dateCreated: "4/19/2021",
      address1: "2 Sommers Point",
      zipCode: "34605",
      city: "Brooksville",
      state: "FL",
    },
    {
      id: 77,
      firstName: "Jammal",
      lastName: "Ahrend",
      email: "jahrend24@vinaora.com",
      companyName: "O'Reilly-Breitenberg",
      clientType: "INDIVIDUAL",
      dateCreated: "10/14/2020",
      address1: "35959 Gina Parkway",
      zipCode: "46231",
      city: "Indianapolis",
      state: "IN",
    },
    {
      id: 78,
      firstName: "Si",
      lastName: "Conklin",
      email: "sconklin25@cdbaby.com",
      companyName: "Kulas Inc",
      clientType: "COMPANY",
      dateCreated: "1/11/2021",
      address1: "9 Merrick Place",
      zipCode: "20029",
      city: "Washington",
      state: "DC",
    },
    {
      id: 79,
      firstName: "Rayner",
      lastName: "Gerriessen",
      email: "rgerriessen26@springer.com",
      companyName: "Mertz Inc",
      clientType: "INDIVIDUAL",
      dateCreated: "2/22/2021",
      address1: "7 Ryan Hill",
      zipCode: "66622",
      city: "Topeka",
      state: "KS",
    },
    {
      id: 80,
      firstName: "Sherwin",
      lastName: "Beek",
      email: "sbeek27@geocities.com",
      companyName: "Stoltenberg-Baumbach",
      clientType: "COMPANY",
      dateCreated: "9/25/2020",
      address1: "6 Fallview Court",
      zipCode: "87115",
      city: "Albuquerque",
      state: "NM",
    },
    {
      id: 81,
      firstName: "Carny",
      lastName: "Sandars",
      email: "csandars28@elpais.com",
      companyName: "Hand LLC",
      clientType: "INDIVIDUAL",
      dateCreated: "6/6/2021",
      address1: "6544 Eagan Trail",
      zipCode: "51110",
      city: "Sioux City",
      state: "IA",
    },
    {
      id: 82,
      firstName: "Nancie",
      lastName: "Hunn",
      email: "nhunn29@msu.edu",
      companyName: "Keeling Inc",
      clientType: "COMPANY",
      dateCreated: "3/6/2021",
      address1: "189 Chive Parkway",
      zipCode: "48232",
      city: "Detroit",
      state: "MI",
    },
    {
      id: 83,
      firstName: "Jodie",
      lastName: "Petrenko",
      email: "jpetrenko2a@people.com.cn",
      companyName: "Klein Inc",
      clientType: "INDIVIDUAL",
      dateCreated: "11/20/2020",
      address1: "1771 Carey Street",
      zipCode: "37405",
      city: "Chattanooga",
      state: "TN",
    },
    {
      id: 84,
      firstName: "Jilli",
      lastName: "Renon",
      email: "jrenon2b@toplist.cz",
      companyName: "Mertz Inc",
      clientType: "INDIVIDUAL",
      dateCreated: "1/6/2021",
      address1: "71 Eggendart Terrace",
      zipCode: "61825",
      city: "Champaign",
      state: "IL",
    },
    {
      id: 85,
      firstName: "Deina",
      lastName: "Caple",
      email: "dcaple2c@sourceforge.net",
      companyName: "Bosco-Turcotte",
      clientType: "INDIVIDUAL",
      dateCreated: "1/4/2021",
      address1: "7 Del Sol Trail",
      zipCode: "25326",
      city: "Charleston",
      state: "WV",
    },
    {
      id: 86,
      firstName: "Dell",
      lastName: "Saffrin",
      email: "dsaffrin2d@samsung.com",
      companyName: "Stroman LLC",
      clientType: "COMPANY",
      dateCreated: "3/14/2021",
      address1: "4 Stuart Place",
      zipCode: "79116",
      city: "Amarillo",
      state: "TX",
    },
    {
      id: 87,
      firstName: "Britte",
      lastName: "Volant",
      email: "bvolant2e@mapy.cz",
      companyName: "Schaden-Maggio",
      clientType: "INDIVIDUAL",
      dateCreated: "8/3/2021",
      address1: "17 Bultman Point",
      zipCode: "95833",
      city: "Sacramento",
      state: "CA",
    },
    {
      id: 88,
      firstName: "Lennard",
      lastName: "Niven",
      email: "lniven2f@toplist.cz",
      companyName: "Johnston LLC",
      clientType: "COMPANY",
      dateCreated: "4/16/2021",
      address1: "5 Welch Avenue",
      zipCode: "75185",
      city: "Mesquite",
      state: "TX",
    },
    {
      id: 89,
      firstName: "Orelee",
      lastName: "Sallans",
      email: "osallans2g@networkadvertising.org",
      companyName: "Gaylord-Stanton",
      clientType: "COMPANY",
      dateCreated: "7/5/2021",
      address1: "3043 Ruskin Way",
      zipCode: "34642",
      city: "Seminole",
      state: "FL",
    },
    {
      id: 90,
      firstName: "Petrina",
      lastName: "Simmens",
      email: "psimmens2h@weather.com",
      companyName: "Emmerich, Rath and Spencer",
      clientType: "COMPANY",
      dateCreated: "11/5/2020",
      address1: "08 Mallory Road",
      zipCode: "22156",
      city: "Springfield",
      state: "VA",
    },
    {
      id: 91,
      firstName: "Lexi",
      lastName: "Speariett",
      email: "lspeariett2i@bloglovin.com",
      companyName: "Lakin LLC",
      clientType: "INDIVIDUAL",
      dateCreated: "12/2/2020",
      address1: "66641 Mallard Point",
      zipCode: "25770",
      city: "Huntington",
      state: "WV",
    },
    {
      id: 92,
      firstName: "Joana",
      lastName: "Crollman",
      email: "jcrollman2j@wix.com",
      companyName: "Dietrich Inc",
      clientType: "COMPANY",
      dateCreated: "7/20/2021",
      address1: "0 Bayside Drive",
      zipCode: "11205",
      city: "Brooklyn",
      state: "NY",
    },
    {
      id: 93,
      firstName: "Hali",
      lastName: "Ipsley",
      email: "hipsley2k@rakuten.co.jp",
      companyName: "Streich, Abbott and Rosenbaum",
      clientType: "COMPANY",
      dateCreated: "5/26/2021",
      address1: "35527 Old Gate Crossing",
      zipCode: "27157",
      city: "Winston Salem",
      state: "NC",
    },
    {
      id: 94,
      firstName: "Darnall",
      lastName: "Demko",
      email: "ddemko2l@wp.com",
      companyName: "Brekke LLC",
      clientType: "INDIVIDUAL",
      dateCreated: "11/6/2020",
      address1: "41733 Gale Hill",
      zipCode: "35487",
      city: "Tuscaloosa",
      state: "AL",
    },
    {
      id: 95,
      firstName: "Zelda",
      lastName: "Luberto",
      email: "zluberto2m@gov.uk",
      companyName: "Gaylord Group",
      clientType: "COMPANY",
      dateCreated: "9/21/2020",
      address1: "36287 Swallow Hill",
      zipCode: "32808",
      city: "Orlando",
      state: "FL",
    },
    {
      id: 96,
      firstName: "Aloisia",
      lastName: "Karel",
      email: "akarel2n@sohu.com",
      companyName: "Collier, O'Reilly and Ortiz",
      clientType: "INDIVIDUAL",
      dateCreated: "12/27/2020",
      address1: "5174 Cambridge Place",
      zipCode: "18763",
      city: "Wilkes Barre",
      state: "PA",
    },
    {
      id: 97,
      firstName: "Cleveland",
      lastName: "Caroll",
      email: "ccaroll2o@tamu.edu",
      companyName: "O'Connell, Strosin and Runolfsdottir",
      clientType: "COMPANY",
      dateCreated: "7/11/2021",
      address1: "532 Twin Pines Junction",
      zipCode: "94245",
      city: "Sacramento",
      state: "CA",
    },
    {
      id: 98,
      firstName: "Deedee",
      lastName: "Mowsley",
      email: "dmowsley2p@wisc.edu",
      companyName: "Thiel LLC",
      clientType: "COMPANY",
      dateCreated: "7/19/2021",
      address1: "8414 Continental Crossing",
      zipCode: "63180",
      city: "Saint Louis",
      state: "MO",
    },
    {
      id: 99,
      firstName: "Nichol",
      lastName: "Chapling",
      email: "nchapling2q@networksolutions.com",
      companyName: "Heaney and Sons",
      clientType: "INDIVIDUAL",
      dateCreated: "9/7/2020",
      address1: "118 Eastwood Hill",
      zipCode: "32575",
      city: "Pensacola",
      state: "FL",
    },
    {
      id: 100,
      firstName: "Meryl",
      lastName: "Frankling",
      email: "mfrankling2r@nsw.gov.au",
      companyName: "Osinski-Mante",
      clientType: "COMPANY",
      dateCreated: "2/18/2021",
      address1: "26269 Pearson Hill",
      zipCode: "20073",
      city: "Washington",
      state: "DC",
    },
  ];
}
